# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20170315_2016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='user_details',
        ),
    ]
